version: "3"

services:
  backend:
    build: "./barbershop"
    ports:
      - "3333:3333"
    environment:
      # host
      VIRTUAL_HOST: app2.mercadocf.site
      LETSENCRYPT_HOST: app2.mercadocf.site
      LETSENCRYPT_EMAIL: codigoaberto.info@gmail.com
      # env
      APP_SECRET: SOME_SECRET_HERE
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: SOME_SECRET_HERE
      DB_NAME: gobarber
      DB_PORT: 5432
      MONGO_URL: mongodb://mongo:27017/gobarger
      REDIS_HOST: cache
      REDIS_PORT: 6379

  web:
    build: "./barberweb"
    ports:
      - "8001:8001"
    environment:
      VIRTUAL_HOST: app.mercadocf.site
      LETSENCRYPT_HOST: app.mercadocf.site
      LETSENCRYPT_EMAIL: codigoaberto.info@gmail.com
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      TZ: "America/Sao_Paulo"
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      VIRTUAL_HOST: adminer.mercadocf.site
      LETSENCRYPT_HOST: adminer.mercadocf.site
      LETSENCRYPT_EMAIL: codigoaberto.info@gmail.com
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017
    volumes:
      - ./mongodata:/data/db
  redisdb:
    image: redis
    restart: always
    container_name: cache
    hostname: redisdb
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379

networks:
  default:
    external:
      name: nginx-proxy
